ODROIDGO3-UBOOT-CONFIG

# Memory Map (Standard RK3326 Handheld Layout)
setenv kernel_addr_r  0x02000000
setenv fdt_addr_r     0x01f00000
setenv ramdisk_addr_r 0x04000000

# Stability Settings
#setenv fdt_high     0xffffffff
#setenv initrd_high 0xffffffff

# Boot Arguments
setenv bootargs "boot=LABEL=BOOT disk=LABEL=ROOT quiet rootwait rw console=tty0 ssh consoleblank=0 video=DSI-1:720x720@60 systemd.show_status=0 loglevel=4 panic=20
"

#root=PARTUUID=3b775aed-02

# Boot Source Detection
#echo "Loading Alpine OS from mmc 1:1..."

load mmc 1:1 ${kernel_addr_r} Image
load mmc 1:1 ${ramdisk_addr_r} uInitrd
load mmc 1:1 ${fdt_addr_r} rk3326-r36ultra-linux.dtb

#echo "--- Starting Kernel ---"

booti ${kernel_addr_r} - ${ramdisk_addr_r} - ${fdt_addr_r}
